
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const DELETE_EXERCISE = 'DELETE_EXERCISE'
export const FETCH_EXERCISES = 'FETCH_EXERCISES'
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE'
export const EXERCISES_SUCCESS = 'EXERCISES_SUCCESS'
export const EXERCISES_FAILURE ='EXERCISES_FAILURE'

export const GET_EXERCISE ='GET_EXERCISE'
export const EXERCISE_SUCCESS ='EXERCISE_SUCCESS'
export const EXERCISE_FAILURE ='EXERCISE_FAILURE'


export const GET_USER = 'GET_USER'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const USER_SUCESS='USER_SUCCESS'
export const USER_FAILURE='USER_FAILURE'

export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const LOGIN_SUCESS='LOGIN_SUCESS'
export const LOGIN_FAILURE='LOGIN_FAILURE'

export const UPLOAD = 'UPLOAD'