
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const DELETE_EXERCISE = 'DELETE_EXERCISE'
export const FETCH_EXERCISES = 'FETCH_EXERCISES'
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE'
export const GET_EXERCISE ='GET_EXERCISE'
export const GET_WORKOUT = 'GET_WORKOUT'
export const ADD_WORKOUT = 'ADD_WORKOUT'
export const DELETE_WORKOUT = 'DELETE_WORKOUT'
export const UPDATE_WORKOUT = 'UPDATE_WORKOUT'
export const SUCCESS = 'SUCCESS'
export const FAILURE ='FAILURE'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const GET_USER = 'GET_USER'
export const UPDATE_USER = 'UPDATE_USER'